# Generated by Django 5.1.4 on 2025-05-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_slug_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
            preserve_default=False,
        ),
    ]
